Project = new Mongo.Collection('project')
Domains = new Mongo.Collection('domains')
IPs = new Mongo.Collection('ips')
Hashes = new Mongo.Collection('hashes')
BigCounts = new Mongo.Collection('bigcounts')
